# Minitest tests being regular Ruby classes will raise unwanted metrics offenses
Metrics:
  Exclude:
    - "test/**/*"

# We use the compact class definition for test files
Style/ClassAndModuleChildren:
  Exclude:
    - "lib/hanami/minitest/generators/templates/**/*"
    - "test/**/*"
